### ISSUE TITLE
A potential bug of visual_data_handler.py

### ISSUE THREAD

**Issue by Hiusam** [nickgkan/beauty_detr#14]
Hi, in `src/visual_data_handlers.py`:
```
def load_point_cloud(self, keep_points=50000):
        """Load point-cloud information."""
        # Load labels
        label = None
        if osp.exists(self.scan_id + '_vh_clean_2.labels.ply'): # This will always be False
            data = PlyData.read(osp.join(
                self.top_scan_dir,
                self.scan_id, self.scan_id + '_vh_clean_2.labels.ply'
            ))
            label = np.asarray(data.elements[0].data['label'])
```
`osp.exists(self.scan_id + '_vh_clean_2.labels.ply')` will always be False since you seem to forget to add `self.top_scan_dir` and `self.scan_id`. This will result in `label` being None and will throw an error when calling `self.get_object_semantic_label()`

Will this affect the exp results, though no error occurred when I ran the codes?

**Comment by nickgkan** [comment]
Hi, at no point we use the semantic labels of the point cloud, so that's why it works.
You're right, label is always None, but get_object_semantic_label is never used. We just forgot to delete that part when we cleaned the code.

**Comment by Hiusam** [comment]
Ok, thanks.
