### ISSUE TITLE
Regarding the pre-trained checkpoint

### ISSUE THREAD

**Issue by soham-joshi** [nickgkan/beauty_detr#15]
Hi @ayushjain1144, have you made the pre-trained checkpoint of BUTD-DETR (CLS) on ScanRefer public? If yes could you share the same?
Thanks!

**Comment by nickgkan** [comment]
Hi,
The ScanRefer benchmark does not consider the CLS setup, so we haven't trained a model for that recently.
Since you were able to reproduce the rest of the results, you can try to train on this setup.

**Comment by soham-joshi** [comment]
Cool, got it. Thank you @nickgkan !
