### ISSUE TITLE
Labels not updated for random_utt

### ISSUE THREAD

**Issue by soham-joshi** [nickgkan/beauty_detr#18]
Hi @ayushjain1144 , While object detection is trained on ScanNet dataset, if there's a random utterance created why aren't the labels updated reference: [line 730 in joint_det_dataset.py](https://github.com/nickgkan/butd_detr/blob/main/src/joint_det_dataset.py#L730)?

Thanks in advance!

**Comment by nickgkan** [comment]
Hi, this variable is used to fill the ret_dict['sem_cls_label'] field which is only used when evaluating object detection. Random detection prompts are used only during co-training with a referential grounding dataset. So ret_dict['sem_cls_label'] is not used in that case and thus _labels is also not used.

**Comment by soham-joshi** [comment]
Okay. 
Another query: is there a reason only a fixed set of classes (as in DC18 = ScannetDatasetConfig(num_classes=18) ) was selected for object detection?

**Comment by nickgkan** [comment]
The standard ScanNet object detection benchmark contains these 18 classes, see Group-Free/Votenet/etc, this setup is the same as theirs.

**Comment by soham-joshi** [comment]
Got it, Thanks for the response @nickgkan !
