### ISSUE TITLE
Regarding predictions

### ISSUE THREAD

**Issue by soham-joshi** [nickgkan/beauty_detr#19]
Hi @ayushjain1144 @nickgkan 
I wanted to do an error analysis of the trained model. To do so, I wanted to check the model's predictions and ground-truth answers. Is there a part of the code already which can export the predictions for error analysis?
If not, I would be grateful if you could provide insights on how to write a script for the same. 

Thanks in advance!

**Comment by ayushjain1144** [comment]
Hi, We don't have such a script. Maybe [this script](https://github.com/facebookresearch/votenet/blob/main/demo.py) could help as a starting point.

**Comment by soham-joshi** [comment]
Okay, will check it out! Thank you @ayushjain1144!
