### ISSUE TITLE
Default Configuration for SR3D

### ISSUE THREAD

**Issue by soham-joshi** [nickgkan/beauty_detr#22]
Hi @ayushjain1144 @nickgkan ,

A small query, what is the starting learning rate used for the experiments in Tables 6 and 7? The default configuration according to the [code ](https://github.com/nickgkan/butd_detr/blob/main/main_utils.py#L77) says --lr=1e-3, --lr_backbone=1e-4, and --text_encoder_lr=1e-5. But the script---[train_test_cls.sh](https://github.com/nickgkan/butd_detr/blob/main/scripts/train_test_cls.sh#L7) follows  --lr=1e-4, --lr_backbone=1e-3, and --text_encoder_lr=1e-5.

Could you clarify the required configuration, please?

Thanks in advance!

**Comment by ayushjain1144** [comment]
Hi @soham-joshi, [train_test_cls.sh](https://github.com/nickgkan/butd_detr/blob/main/scripts/train_test_cls.sh#L7) has the right configurations.

**Comment by soham-joshi** [comment]
Great, thanks for the prompt response!
