### ISSUE TITLE
Performance about the Group-Free 3D object detector trained to detect 485 object categories in ScanNet

### ISSUE THREAD

**Issue by ZCMax** [nickgkan/beauty_detr#25]
Thanks for your paper and code, I've got a question about the Group-Free 3D object detector trained to detect 485 object categories in ScanNet, can you offer the pre-trained checkpoints or some related per-class performance?

**Comment by ayushjain1144** [comment]
Hi, here are the pre-trained weights: https://drive.google.com/file/d/1JwMTOaMWfK0JgOBBHU_2oBGXp9ORo9Q3/view?usp=sharing

We also provide the box outputs in the ReadMe, maybe you could use it to calculate its mAP (from what I vaguel remember, it was around 58% computed on all 485 classes. but this was long time back, so i am not sure)
