### ISSUE TITLE
requirements.txt-butd_detr2d

### ISSUE THREAD

**Issue by nsaadati** [nickgkan/beauty_detr#29]
hi
for these three lines in  I'm getting errors(ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory:) how I can fix it?
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1634095647912/work
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1648857110829/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work

**Comment by ayushjain1144** [comment]
Hi, you can just delete @ and anything afterwards. I pushed a fix as well.

**Comment by nsaadati** [comment]
hi link for coco 2014 dataset it does not work anymore can you help me find the correct link?

**Comment by ayushjain1144** [comment]
Hi, I just checked, the link works for me.
