### ISSUE TITLE
the confidence threshold you set for the pretrained detector

### ISSUE THREAD

**Issue by linhaojia13** [nickgkan/beauty_detr#30]
As you mentioned in the papers: 
>  ... Group-Free detector [33] for 3D point clouds pre-trained on a vocabulary of 485 object categories on ScanNet [8]. The detected box proposals that surpass a **confidence threshold** are encoded using a box proposal encoder ...

Could you please tell me the **confidence threshold** you set for the pretrained Group-Free detector?

**Comment by ayushjain1144** [comment]
This is what we used:

```
eval_config_dict = {'remove_empty_box': True, 'use_3d_nms': True, 'nms_iou': 0.25,
'use_old_type_nms': False, 'cls_nms': False, 'per_class_proposal': False,
'conf_thresh': 0.5, 'dataset_config': DC}
```

Note that we didn't really play around with these, so they may not be optimal.

**Comment by linhaojia13** [comment]
> This is what we used:
> 
> ```
> eval_config_dict = {'remove_empty_box': True, 'use_3d_nms': True, 'nms_iou': 0.25,
> 'use_old_type_nms': False, 'cls_nms': False, 'per_class_proposal': False,
> 'conf_thresh': 0.5, 'dataset_config': DC}
> ```
> 
> Note that we didn't really play around with these, so they may not be optimal.

Thank you very much！
