### ISSUE TITLE
Questions of loading the pretrained checkpoint into GroupFree3D

### ISSUE THREAD

**Issue by ZCMax** [nickgkan/beauty_detr#31]
Since I found that the pertained checkpoints you mentioned was trained on 485 classes, I want to directly load the checkpoints into Group-Free-3D model and inference to see the performance. However, when I load the model, the error occurs:
![image](https://github.com/nickgkan/butd_detr/assets/36950400/6a2c67a1-c802-4326-8241-81023a1ab5e2)
Thanks very much!

**Comment by ayushjain1144** [comment]
Hi, this is because the original group free is setup to train on 18 classes while the checkpoint is trained on 485 (which is why you see 18->485 inconsistencies). you would need to make changes to dataloader to load ground truths for 485 classes (similar to `joint_det_dataset`) and the model to predict 485 classes instead of 18.

**Comment by ZCMax** [comment]
Sorry but I think I've changed the class number to 485 in Groupfree3d, the error shows the `copying a param with shape [18] from checkpoint to the current model [485]'. If I do not make mistakes, it seems that the provided checkpoint is trained on 18 classes?

**Comment by ayushjain1144** [comment]
Hi, yes you are right, we supplied you the wrong checkpoint. Here is the correct one: https://drive.google.com/file/d/11ka2r1NGNpY3lvmV-7qF2g75e63Bpmno/view?usp=sharing.

**Comment by ZCMax** [comment]
Thank you so much, another thing is that the model on ScanNet dataset relies on the `scannet_means.npz` file which only contains 18 classes information provided in original GroupFree3D codebase, I wonder whether did you calculate based on ScanNet dataset annotations to form a new `npz` file including 485 classes? Is it possible to offer the new `scannet_means.npz` file? Thanks very much！

**Comment by ayushjain1144** [comment]
this might be it: https://drive.google.com/file/d/1TX_d5CjfSvnQC_wcZ1aWtnwXhlNUBQfg/view?usp=sharing

**Comment by ZCMax** [comment]
Thank you so much~ I can do inference on the 485 classes on Group-Free-3D and get the results using your provided checkpoint !
