### ISSUE TITLE
About the soft token prediction

### ISSUE THREAD

**Issue by ZCMax** [nickgkan/beauty_detr#38]
Since the results of `evaluate_bbox_by_contrast` are higher than `evaluate_bbox_by_span`, I have a question that if the soft prediction loss is removed, what would happen to the final results while only keeping contrastive alignment loss? Is alignment loss enough for model training?

**Comment by nickgkan** [comment]
Hi,
While we didn't thoroughly experiment on this, we had some indications that we need both losses to achieve the reported performance. It could be the case that with some different weighting one of the loss terms can be removed, but we did not extensively try that.
