### ISSUE TITLE
Hi , it's a great work. On your paper you show the time training on one v100 in Flickr30k is more than 2000 hours. It is a large number.  Then how long will the modal take to train on the 3D grounding dataset.

### ISSUE THREAD

**Issue by 618QRC** [nickgkan/beauty_detr#4]

**Comment by nickgkan** [comment]
Depends on your hardware. With our hyperparameters on an NVIDIA A100 it takes approximately one day for SR3D, up to two days for NR3D and ScanRefer. If you train on a V100 you can expect similar times or slightly more.
