### ISSUE TITLE
Training on 3D referential datasets, evaluating on 3D detection datasets

### ISSUE THREAD

**Issue by ZCMax** [nickgkan/beauty_detr#42]
In table 10, I want to know the method like "BUTD-DETR trained on SR3D/NR3D/ScanRefer" is only trained on referential data, or on referential data and detection prompts?  If latter,  I wonder we only train BUTD-DETR on referential data without detection prompt, can the trained model be directed evaluated on 3D detection benchmark, by replacing the visual grounding utterance with detection prompts?

**Comment by ZCMax** [comment]
Anther question is that: if we want to detect the tv in a scene, I find that the extracted text feature of `tv` of these two utterances: `"tv. cabinet. monitor."`  and `"tv. book. table." ` different,  whether the detection prompt during evaluation and training should be the same?

**Comment by ayushjain1144** [comment]
`In table 10, I want to know the method like "BUTD-DETR trained on SR3D/NR3D/ScanRefer" is only trained on referential data, or on referential data and detection prompts?` Latter

`If latter, I wonder we only train BUTD-DETR on referential data without detection prompt, can the trained model be directed evaluated on 3D detection benchmark, by replacing the visual grounding utterance with detection prompts?`: I think the detection prompt would be quite out of distribution if you only train for visual grounding, so I don't think it would work.

`Anther question is that: if we want to detect the tv in a scene, I find that the extracted text feature of tv of these two utterances: "tv. cabinet. monitor." and "tv. book. table."  different, whether the detection prompt during evaluation and training should be the same?`: During training, I think we train by randomly shuffling the detection prompts. So even if TV 
"feature" is different, I would expect it to still work as queries can cross-attend to text and adapt based on it.

**Comment by ZCMax** [comment]
Thanks so much for your reply~
