### ISSUE TITLE
Why use predicted spans instead of ground truth spans during the training process?

### ISSUE THREAD

**Issue by Daniellli** [nickgkan/beauty_detr#43]
hi, sorry for bothering you again.

Why use predicted spans instead of ground truth spans during the training process  such as [this line](https://github.com/nickgkan/butd_detr/blob/10570e0b6826d4a236b18c2c8fac5903866e1c60/models/losses.py#L441).

thank you for your time

**Comment by ayushjain1144** [comment]
Hi, we wanted to train the model to be robust to imperfections in the spans, hence we use the imperfect predicted spans instead of gt spans.
