### ISSUE TITLE
About 'couch' in `DC18.type2class`

### ISSUE THREAD

**Issue by linhaojia13** [nickgkan/beauty_detr#44]
Hi, thank you very for your open codes! It really do me favour in my several works.

In this [line](https://github.com/nickgkan/butd_detr/blob/10570e0b6826d4a236b18c2c8fac5903866e1c60/src/joint_det_dataset.py#L251C23-L251C38), `DC18.type2class` is used to mapping the nyu_labels to 18-class id:
```
labels = [DC18.type2class.get(lbl, 17) for lbl in nyu_labels]
```
When I dig into `class ScannetDatasetConfig` in [model_util_scannet.py](https://github.com/nickgkan/butd_detr/blob/10570e0b6826d4a236b18c2c8fac5903866e1c60/data/model_util_scannet.py#L22C18-L22C29), I find the key for id `3` is `couch`:
```
    self.type2class = {'cabinet': 0, 'bed': 1, 'chair': 2, 'couch': 3, 'table': 4, 'door': 5,
                       'window': 6, 'bookshelf': 7, 'picture': 8, 'counter': 9, 'desk': 10, 'curtain': 11,
                       'refrigerator': 12, 'shower curtain': 13, 'toilet': 14, 'sink': 15, 'bathtub': 16,
                       'other furniture': 17}
```
However, `couch` is the raw name for scannet. The nyu40class name should be `sofa`.

This typo would make `DC18.type2class` map `sofa` to id `17` but not `3`, just like:
```
(Pdb) nyu_labels
['window', 'window', 'table', 'counter', 'otherstructure', 'curtain', 'curtain', 'desk', 'cabinet', 'floor', 'sink', 'otherprop', 'otherfurniture', 'otherfurniture', 'otherfurniture', 'television', 'pillow', 'otherprop', 'otherprop', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'otherprop', 'otherprop', 'otherprop', 'otherprop', 'sofa', 'refridgerator', 'table', 'table', 'toilet', 'bed', 'cabinet', 'cabinet', 'cabinet', 'cabinet', 'cabinet', 'cabinet', 'otherprop', 'otherprop', 'otherprop', 'otherprop', 'otherprop', 'night stand', 'night stand', 'otherprop', 'otherprop', 'otherprop', 'door', 'ceiling', 'shelves', 'otherprop', 'otherprop', 'otherprop', 'otherprop', 'otherprop', 'otherprop', 'door', 'mirror', 'door', 'otherprop']
(Pdb) labels
[6, 6, 4, 9, 17, 11, 11, 10, 0, 17, 15, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 4, 4, 14, 1, 0, 0, 0, 0, 0, 0, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 5, 17, 17, 17, 17, 17, 17, 17, 17, 5, 17, 5, 17]
(Pdb)
```

**Comment by ayushjain1144** [comment]
good catch! 

Do you find this affecting anything in terms of training / downstream evaluations? (I might be wrong, but i don't think it should)

**Comment by RunsenXu** [comment]
There is another similar problem here. The raw name of refrigerator is "refrigerator" but for nyu40class, it is "refridgerator", which makes all refrigerator mapping to "others". This bug **does not** exist in the ScanRefer codes as the tsv file ScanRefer uses is consistent for refrigerator, but I found the tsv file used in VoteNet also uses "refridgerator".

Maybe these errors affect the calculation of "unique" and "multi".
