### ISSUE TITLE
Hi, I have a following question here for butd_cls mode.

### ISSUE THREAD

**Issue by WeitaiKang** [nickgkan/beauty_detr#46]
Hi, I have a following question here for butd_cls mode.

In [Link](https://github.com/nickgkan/butd_detr/blob/10570e0b6826d4a236b18c2c8fac5903866e1c60/src/joint_det_dataset.py#L721), you get the **detected_class_ids** from 'data/cls_results.json', which you mentioned in other issues that it is the predicted class result from pointnet++(pretrained on ScanNet). 

However, in the standard mode, where butd_cls = False and butd_gt = False, your **detected_class_ids** comes from [Link](https://github.com/nickgkan/butd_detr/blob/10570e0b6826d4a236b18c2c8fac5903866e1c60/src/joint_det_dataset.py#L572). And it is also the predicted class result from pointnet++(pretrained on ScanNet), but with additional DC.nyu40id2class mapping.

I have checked both of the above two **detected_class_ids** and find that they are difference. Do i miss something here?

ps: I remove the **corrupt** [Link](https://github.com/nickgkan/butd_detr/blob/10570e0b6826d4a236b18c2c8fac5903866e1c60/src/joint_det_dataset.py#L616) to avoid mistake.

_Originally posted by @WeitaiKang in https://github.com/nickgkan/butd_detr/issues/11#issuecomment-1872337546_

**Comment by ayushjain1144** [comment]
Hi,

"In the standard mode, where butd_cls = False and butd_gt = False, your
*detected_class_ids* comes from Link
<https://github.com/nickgkan/butd_detr/blob/10570e0b6826d4a236b18c2c8fac5903866e1c60/src/joint_det_dataset.py#L572>.
And it is also the predicted class result from pointnet++(pretrained on
ScanNet), but with additional DC.nyu40id2class mapping." these detected IDs
are not pointnet++ predictions, but class predictions from the group free
detector (we get both detected objects and classes from it).

When butd_gt is true, both of these are replaced by gt objects and classes.
When butd_cls=True, then boxes are gt and classes come from pointnet++.

Best
Ayush

**Comment by WeitaiKang** [comment]
Thank you for your prompt response! I now have a full understanding.
