### ISSUE TITLE
About scanrefer predicted spans?

### ISSUE THREAD

**Issue by HyperbolicCurve** [nickgkan/beauty_detr#52]
Hi👋, may I ask how to get scanrefer_pred_spans_train.json and scanrefer_pred_spans_val.json? I didn't find the method in the paper or the code.

**Comment by ayushjain1144** [comment]
Hi, It is in `data preparation` section of README. (for eg: scanrefered val: https://zenodo.org/record/7363895/files/scanrefer_pred_spans_val.json?download=1 and scanrefer train: https://zenodo.org/record/7363895/files/scanrefer_pred_spans_train.json?download=1)

**Comment by HyperbolicCurve** [comment]
> Hi, It is in `data preparation` section of README. (for eg: scanrefered val: https://zenodo.org/record/7363895/files/scanrefer_pred_spans_val.json?download=1 and scanrefer train: https://zenodo.org/record/7363895/files/scanrefer_pred_spans_train.json?download=1)

Sorry, I mean the code to generate the scanrefer_pred_spans🤔

**Comment by ayushjain1144** [comment]
its here: https://github.com/nickgkan/butd_detr/blob/main/src/text_cls.py
