### ISSUE TITLE
CUDA kernel failed : initialization error

### ISSUE THREAD

**Issue by ZheningHuang** [nickgkan/beauty_detr#6]
```

CUDA kernel failed : initialization error
void furthest_point_sampling_kernel_wrapper(int, int, int, const float*, float*, int*) at L:233 in _ext_src/src/sampling_gpu.cu
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 255) local_rank: 0 (pid: 15542) of binary: ~/miniconda3/envs/vg_3d/bin/python
```

I wonder if the author has seen this error before. I successfully set up init.sh file but still got this error.

**Comment by ayushjain1144** [comment]
sometimes re-installing pointnet2 helps. you can try the following:
- rm -rf pointnet2/build (to delete the old binaries)
- sh init.sh

let us know if the error still persists (more details would help: for example the logs you see when you execute init.sh)

**Comment by ZheningHuang** [comment]
Thanks this problem is solved by properly config CUDA versions and reinstall pointnet2
